// Mocks generated by Mockito 5.4.6 from annotations
// in apiconnectapp/test/viewmodels/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:apiconnectapp/models/article.dart' as _i3;
import 'package:apiconnectapp/services/connectivity_service.dart' as _i7;
import 'package:apiconnectapp/services/news_api.dart' as _i6;
import 'package:apiconnectapp/services/weather_api.dart' as _i4;
import 'package:apiconnectapp/services/weather_api_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWeatherResponse_0 extends _i1.SmartFake
    implements _i2.WeatherResponse {
  _FakeWeatherResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNewsResponse_1 extends _i1.SmartFake implements _i3.NewsResponse {
  _FakeNewsResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WeatherApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherApi extends _i1.Mock implements _i4.WeatherApi {
  MockWeatherApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.WeatherResponse> getWeather(
    String? cityName,
    String? apiKey,
    String? units,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWeather, [cityName, apiKey, units]),
            returnValue: _i5.Future<_i2.WeatherResponse>.value(
              _FakeWeatherResponse_0(
                this,
                Invocation.method(#getWeather, [cityName, apiKey, units]),
              ),
            ),
          )
          as _i5.Future<_i2.WeatherResponse>);
}

/// A class which mocks [NewsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsApi extends _i1.Mock implements _i6.NewsApi {
  MockNewsApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.NewsResponse> getTopHeadlines(
    String? country,
    String? apiKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTopHeadlines, [country, apiKey]),
            returnValue: _i5.Future<_i3.NewsResponse>.value(
              _FakeNewsResponse_1(
                this,
                Invocation.method(#getTopHeadlines, [country, apiKey]),
              ),
            ),
          )
          as _i5.Future<_i3.NewsResponse>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i7.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> hasInternetConnection() =>
      (super.noSuchMethod(
            Invocation.method(#hasInternetConnection, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
